### ISSUE TITLE
hypergit web crashes

### ISSUE THREAD

**Issue by Gozala** [noffle/hypergit#3]
`hypergit web` crashes unless `git push swarm` has being done already.

```
gitverse live on http://localhost:9111
/Users/gozala/.config/yarn/global/node_modules/pull-stream/sinks/drain.js:22
                throw end
                ^

Error: Invalid name 'undefined'
    at Object.R.resolveRef (/Users/gozala/.config/yarn/global/node_modules/pull-git-repo/index.js:273:15)
    at Object.R.getRef (/Users/gozala/.config/yarn/global/node_modules/pull-git-repo/index.js:303:8)
    at Object.R.getCommit (/Users/gozala/.config/yarn/global/node_modules/pull-git-repo/index.js:550:8)
    at /Users/gozala/.config/yarn/global/node_modules/pull-git-repo/index.js:314:10
    at /Users/gozala/.config/yarn/global/node_modules/pull-git-repo/index.js:84:5
    at next (/Users/gozala/.config/yarn/global/node_modules/pull-stream/sinks/drain.js:16:11)
    at sink (/Users/gozala/.config/yarn/global/node_modules/pull-stream/sinks/drain.js:37:9)
    at pull (/Users/gozala/.config/yarn/global/node_modules/pull-stream/pull.js:41:14)
    at /Users/gozala/.config/yarn/global/node_modules/gitverse/index.js:99:9
    at next (/Users/gozala/.config/yarn/global/node_modules/pull-git-repo/index.js:290:9)
```

**Comment by hackergrrl** [comment]
Nice catch @Gozala! I forgot to do something smart in case the repo is empty.

This was a [gitverse](https://github.com/noffle/gitverse) bug (the name of the web interface), and it is now fixed as of `gitverse@1.0.2`! A fresh `npm i -g hypergit` ought to fix this for you. :tada:
